# sudo: false

language: python

python:
  - '3.5'
 # - '3.6'
 # - '3.7'

env:
  - ENV_STRING=pandas0.24.1
    JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
#  - ENV_STRING=pandas0.24.0
#
#  - ENV_STRING=pandas0.23.4
#  - ENV_STRING=pandas0.23.3
#  - ENV_STRING=pandas0.23.2
#  - ENV_STRING=pandas0.23.1
#  - ENV_STRING=pandas0.23.0
#
#  - ENV_STRING=pandas0.22.0
#
#  - ENV_STRING=pandas0.21.1
#  - ENV_STRING=pandas0.21.0
#
#  - ENV_STRING=pandas0.20.3
#  - ENV_STRING=pandas0.20.2
#  - ENV_STRING=pandas0.20.1
#  - ENV_STRING=pandas0.20.0
#
#  - ENV_STRING=pandas0.19.2
#  - ENV_STRING=pandas0.19.1
#  - ENV_STRING=pandas0.19.0
#
  - ENV_STRING=pyspark2.4.0
    JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
#  - ENV_STRING=pyspark2.3.1


dist: xenial

before_install:
  - java -version
  - echo $JAVA_HOME
  - export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
  - sudo add-apt-repository -y ppa:openjdk-r/ppa
  - sudo apt-get -qq update
  - sudo apt-get install -y openjdk-8-jdk --no-install-recommends
  - sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
  - java -version

install:
  - echo $JAVA_HOME
  - travis_retry pip install --upgrade pip
  - travis_retry pip install --upgrade setuptools
  - travis_retry pip install coveralls flake8 tox

script:
  - tox -e $(echo py$TRAVIS_PYTHON_VERSION-$ENV_STRING | tr -d .)

after_success:
  - coveralls --verbose

cache: pip
